### PR TITLE
SCT-1286 add test for alignment stats

### PR DESCRIPTION
**Pull request by Tianhao-Gu**

### CODE REVIEW

**Comment by sychan** [comment]
@Tianhao-Gu Do your tests require the full KBase infrastructure to run, or can they run locally without the rest of kbase?

**Comment by Tianhao-Gu** [comment]
@sychan It can be run locally. Just `kb-sdk test`. That's how I run it.

**Comment by JamesJeffryes** [comment]
@Tianhao-Gu I'm getting the following error in my tests:
```
======================================================================
FAIL: test_bowtie2_aligner_with_sampleset (kb_Bowtie2_Aligner_test.kb_Bowtie2AlignerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/kb/module/test/kb_Bowtie2_Aligner_test.py", line 245, in test_bowtie2_aligner_with_sampleset
    self.assertEqual(align_stats.get('total_reads'), 15254)
AssertionError: 32877 != 15254
```

**Comment by Tianhao-Gu** [comment]
@JamesJeffryes could you run it against appdev? CI RAU is not promoted.

**Comment by sychan** [comment]
@Tianhao-Gu Sorry, I should have followed up. If you can run the tests locally, I think you should setup travis.yml to run the test and display coverage. But I can merge this for now

**Pull request merged**
